server:
  port: 8001

spring:
  application:
    name: spring-ai-redis-rag
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    vectorstore:
      redis:
        initialize-schema: true
        prefix: prefix_spring_ai_alibaba
        index: index_spring_ai_alibaba
  data:
    redis:
      host: localhost
      port: 6379 # Redis服务器连接端口
      password: ${LOCAL_REDIS_PASSWORD}
