server:
  port: 8001

spring:
  application:
    name: spring-ai-deepseek-chat
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#        options:
#          temperature: 0.7
