server:
  port: 8001

spring:
  application:
    name: spring-ai-time-tools

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
#      chat:
#        options:
#          model: qwen-max
    chat:
      observations:
        log-prompt: true
        log-completion: true
